{% set name = "regions" %}
{% set version = "0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ac89875ac8b52277322a54e952d3bd7d1f48510aaf342354e07df005996459ae

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - numpy
    - setuptools
    - pip
  run:
    - python
    - six
    - {{ pin_compatible('numpy') }}
    - astropy

test:
  imports:
    - regions
    - regions.core
    - regions.io
    - regions.shapes

about:
  home: https://github.com/astropy/regions
  license: BSD-3-Clause
  license_file: LICENSE.rst
  license_family: BSD
  summary: Astropy affilated package for region handling
  description: |
    This is an in-development package for region handling based on Astropy.
    The goal is to merge the functionality from pyregion and photutils
    apertures and then after some time propose this package for inclusion in
    the Astropy core.
  doc_url: https://astropy-regions.readthedocs.io
  dev_url: https://github.com/astropy/regions

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
