{% set name = "regions" %}
{% set version = "0.3" %}
{% set hash_type = "sha256" %}
{% set hash_value = "ec98751880020a3e0c861e43412c750240576b09882bd71cdeb67dbcb0ed7618" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 1001
  script: python setup.py install --offline --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - astropy
  run:
    - python
    - astropy
    - astropy-healpix

test:
  imports:
    - regions
    - regions.core
    - regions.io
    - regions.shapes

about:
  home: http://github.com/astropy/regions
  license: BSD 3-clause
  license_family: BSD
  summary: Astropy affilated package for region handling
  description: |
    This is an in-development package for region handling based on Astropy.
    The goal is to merge the functionality from pyregion and photutils
    apertures and then after some time propose this package for inclusion in
    the Astropy core.
  doc_url: http://astropy-regions.readthedocs.io
  dev_url: https://github.com/astropy/regions

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - cdeil
