travis:
  secure: {BINSTAR_TOKEN: o/5wwJH9Klj4Y8W0+GsNKkx8oyX00rBFC6IZ17yJdmrLgcVnF2V1yszw46SRtYyfXK9VF3v6e0jK0X6MjsFlPj5TySV8DoIDRLEDEe/OXYKr0H+zjGgasN75Zl4/Czu3bZ6Ao4DR4yRGYQKCzBRgpku2UBDcb8E4C6f59yDuSMR1E31oXorsY2V7wmfP0GAHwaJGQnHDDJe5p0l9rWKAYg0R4+u1Kk/4xim4EsmPli7MYvay1oNnO96WzZw/Ypt3faEz9UpCGhItfx42lGEWGSBoZOwJOZNmOoLZg30lS2e5OtZpheEqhkB7tikFRlzLAKgil8U21YjK33WvTLp0RgqHAAbVnH0Zpv/FfMMVQWAWJ1gI4I7zXGwUkE7Lg8xD/vb6NgmPRHPkf1gnNn+ry/5/qO5FW8vip6Ih+K39mvFOavihEX9KOO0YFsmRtabEfmyCmAIevyPoeYDCq0RgNzo2hTNNvc8JooU5CaJRLntmjyVybeFT/MDuPCbsXHHDs38ytOryANPQieCbnIPlkEs6yD3WOrsHOOHEhMbgZhc39OVisPRvwI3utw7NNFnug0iRvhpK7RNZ9sj7Qy/d6GPCKVsSClt9JH+O8Le8qRusby/tPaI/ScBjJwQotbRQDcnWb7SKRre70NXr8nDWHX1SorDfcowe8ppVJY2KLAA=}
appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider:
  win: azure
